AVI_CA_DATA_B64: ""
AVI_CLOUD_NAME: ""
AVI_CONTROL_PLANE_HA_PROVIDER: ""
AVI_CONTROLLER: ""
AVI_DATA_NETWORK: ""
AVI_DATA_NETWORK_CIDR: ""
AVI_ENABLE: "false"
AVI_LABELS: ""
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: ""
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: ""
AVI_PASSWORD: ""
AVI_SERVICE_ENGINE_GROUP: ""
AVI_USERNAME: ""
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: tce-mgmt-dk
CLUSTER_PLAN: dev
ENABLE_AUDIT_LOGGING: "false"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: photon
OS_VERSION: "3"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
TKG_IP_FAMILY: ipv4
VSPHERE_CONTROL_PLANE_DISK_GIB: "20"
VSPHERE_CONTROL_PLANE_ENDPOINT: 192.168.171.21
VSPHERE_CONTROL_PLANE_MEM_MIB: "4096"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /RHMLab
VSPHERE_DATASTORE: /RHMLab/datastore/esx-03-local-01
VSPHERE_FOLDER: /RHMLab/vm
VSPHERE_INSECURE: "false"
VSPHERE_NETWORK: /RHMLab/network/DS2-171
VSPHERE_PASSWORD: <encoded:Vk13YXJlMTIzIQ==>
VSPHERE_RESOURCE_POOL: /RHMLab/host/192.168.100.98/Resources
VSPHERE_SERVER: vcenter-01.rhmlab.local
VSPHERE_SSH_AUTHORIZED_KEY: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCszcjMujpG+YmRhVv6yuIVthIwgTKLMxjnpdW65mWEVKc5GGpLr4CvJLNgn65ZcWCk1RZjt21U1OUz+OewcTfyp3gVsSHz9RnjbP0OYHMqBm3/WhGHi1kqJtrQc4wlvaNZSDlWOVmXb4f0D8Vebf4Jfw13VYtW6dn8d7l8RUCWpieRAQt6UvPagaIHwLD1CB2S5WyCMWQCG1PcoWJdpSVdiDSAhWgUVBFcyMvB0SjvFnkviB9iiSD4Tome37y9mLrjWb6bnfWqJFYdXnbKgg759JRscxr9eA/yuM6HnysOHHyZG1R4E883W1urTRN8hgzKgiAZrUOreUdxobh1lwxnOhgVb5M57ohRaTxBURbGWWuoEpuifjbxkmXt3KQP8nIaeFARJZQKQwO+IImxB/Dm5Wr03EojMM3v1myNuzx5SUziH85lqzHm1EIUFOry12JeFYWnIXtCp3a4C+wA5Drm+ofPU7p6TK5P5YemV3ZRuOD45GMUx7nYK2gthuPK3Hk= rudi@rhm-ubuntu-client
VSPHERE_TLS_THUMBPRINT: D8:53:5D:1E:BC:B5:2D:1F:51:CF:DA:61:F1:4E:49:30:99:43:A2:F1
VSPHERE_USERNAME: rudi@rhmlab.local
VSPHERE_WORKER_DISK_GIB: "20"
VSPHERE_WORKER_MEM_MIB: "4096"
VSPHERE_WORKER_NUM_CPUS: "2"
