apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: plex-issuer
  namespace: plex
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
  namespace: plex
spec:
  secretName: plex-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - rhmlab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - plex.tce.rhmlab.local
    - tce-plex.rhmlab.tech
  ipAddresses:
    - 192.168.171.203
  issuerRef:
    name: plex-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: plexserver
  name: plex-httpproxy
  namespace: plex
spec:
  routes:
  - conditions:
    - prefix: /
    pathRewritePolicy:
      replacePrefix:
      - prefix: /
        replacement: /
    services:
    - name: plex-tcp #corresponds to service object
      port: 32400
  virtualhost:
    fqdn: plex.tce.rhmlab.local
    tls:
      secretName: plex-tls
